### ISSUE TITLE
question about mpc and dp

### ISSUE THREAD

**Issue by NcuBluecoffee** [hongzimao/pensieve#43]
hi:
     I want to reproduce your experiment, now i know how to train the rl model, and i just want to plot the figure to compare the different algorithm.but when i put the trained model into the ./test/model, and run rl_no_training.py, it does works. and then i run the bb.py, it also works,but when i try to run mpc.py and dp.py, there have some error: the error information as follows:
Traceback (most recent call last):
  File "dp.py", line 226, in <module>
    main()
  File "dp.py", line 71, in main
    all_cooked_time, all_cooked_bw = load_trace.load_trace()
ValueError: too many values to unpack
--------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "mpc.py", line 272, in <module>
    main()
  File "mpc.py", line 92, in main
    net_env.get_video_chunk(bit_rate)
ValueError: too many values to unpack.
--------------------------------------------------------------------------------------------------
should i did something wrong? and i want to ask where the SIM_DP's result?
what's more ,when i plot the result of sim_rl only ,(i have  changed the SCHEMES), but there another error as follows:
Traceback (most recent call last):
  File "plot_results.py", line 227, in <module>
    main()
  File "plot_results.py", line 99, in main
    time_ms -= time_ms[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
-------------------------------------------------------------------------------------------------------
what's wrong with the code? and if i want to plot the results of all algorithm, what shuould i do.For example, if i want to plot the results of sim_rl and bb, does it work if i change the SCHEMES to SCHEMES=['sim_rl','BB']?
i am very grateful if you can give me some suggestion.looking for your reply.

**Comment by hongzimao** [comment]
The `dp.py` code was actually meant for easier understanding of the optimization problem. In the first line of that code, it says `# Too slow! Use dp.cc instead`. Sorry about the confusion.

**Comment by NcuBluecoffee** [comment]
And why the mpc.py have the same error？

**Comment by hongzimao** [comment]
The first error (too many value to unpack) suggests something wrong with the trace. Did you download the traces?

The second error suggests the result array is empty. Can you print the result and see if there is anything?

You may find this issue useful: https://github.com/hongzimao/pensieve/issues/2

**Comment by confiwent** [comment]
I think the error in  ```mpc.py ```   resulted from an output variable missing, since the function ```get_video_chunk(bit_rate)```  return 8 variables but only 7 variables are assigned.
